name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "It looks like you've had some issues with the project. Fear not, @aaronhma will get this resolved ASAP. Stay tuned!"
        pr-message: 'Thank you for contributing! @aaronhma will review your PR ASAP. Stay tuned!'
