name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue hasn't been active, so I'm marking this as stale. Feel free to re-open this if you need more help! :)"
        stale-pr-message: "Thank you for contributing! This PR hasn't been active, so, I'm marking this as stale. Feel free to re-open this if you want this to be merged! :)"
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
